name = "helfringa"
license = "MIT"
licenselink = "https://github.com/waalge/hugo-theme-helfringa/blob/master/LICENSE.md"
description = "minimal responsive light/dark theme"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.80

[author]
  name = "waalge"
  homepage = "https://github.com/waalge"

[orginal]
  name = "Djordje Atlialp"
  homepage = "https://atlialp.com"
  twitter = "https://twitter.com/rhazdon"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"

